// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID             pgtype.UUID        `json:"id"`
	FromWalletID   int64              `json:"from_wallet_id"`
	ToWalletID     int64              `json:"to_wallet_id"`
	Amount         int64              `json:"amount"`
	Status         string             `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID        int64              `json:"id"`
	Balance   int64              `json:"balance"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
