// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWallet(ctx context.Context, balance int64) (Wallet, error)
	// Segurança extra além do Check Constraint
	CreditWallet(ctx context.Context, arg CreditWalletParams) error
	// Retorna número de linhas afetadas. Se 0, ou saldo insuficiente ou ID errado.
	DebitWallet(ctx context.Context, arg DebitWalletParams) (int64, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	// 🚨 CRÍTICO: "FOR UPDATE" trava a linha até o fim da transação
	GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error
}

var _ Querier = (*Queries)(nil)
