// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    from_wallet_id,
    to_wallet_id,
    amount,
    status,
    idempotency_key
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, from_wallet_id, to_wallet_id, amount, status, idempotency_key, created_at
`

type CreateTransactionParams struct {
	FromWalletID   int64       `json:"from_wallet_id"`
	ToWalletID     int64       `json:"to_wallet_id"`
	Amount         int64       `json:"amount"`
	Status         string      `json:"status"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FromWalletID,
		arg.ToWalletID,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, from_wallet_id, to_wallet_id, amount, status, idempotency_key, created_at FROM transactions
WHERE from_wallet_id = $1 OR to_wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	FromWalletID int64 `json:"from_wallet_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.FromWalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FromWalletID,
			&i.ToWalletID,
			&i.Amount,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
