// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallet.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (balance)
VALUES ($1)
RETURNING id, balance, version, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, balance int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, balance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditWallet = `-- name: CreditWallet :exec

UPDATE wallets
SET balance = balance + $1,
    version = version + 1,
    updated_at = NOW()
WHERE id = $2
`

type CreditWalletParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

// Segurança extra além do Check Constraint
func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) error {
	_, err := q.db.Exec(ctx, creditWallet, arg.Amount, arg.ID)
	return err
}

const debitWallet = `-- name: DebitWallet :execrows
UPDATE wallets
SET balance = balance - $1,
    version = version + 1,
    updated_at = NOW()
WHERE id = $2
  AND balance >= $1
`

type DebitWalletParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

// Retorna número de linhas afetadas. Se 0, ou saldo insuficiente ou ID errado.
func (q *Queries) DebitWallet(ctx context.Context, arg DebitWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, debitWallet, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWallet = `-- name: GetWallet :one
SELECT id, balance, version, created_at, updated_at FROM wallets
WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, balance, version, created_at, updated_at FROM wallets
WHERE id = $1
FOR UPDATE
`

// 🚨 CRÍTICO: "FOR UPDATE" trava a linha até o fim da transação
func (q *Queries) GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET balance = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
`

type UpdateWalletBalanceParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.ID, arg.Balance)
	return err
}
